/** @file

    This program converts binary file to C string.
    SPDX-License-Identifier: WTFPL

*/
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

void show_usage(const char* name)
{
    printf("%s:input_file output_file array_name\nThis program will assume the input file as name of array.\n", name);
    exit(EXIT_FAILURE);
}

int main(int argc, const char* argv[])
{
    if(argc!=4) {
        show_usage(argv[0]);
    }
    FILE *input_file, *output_file;
    input_file = fopen(argv[1],"rb");
    if(!input_file) {
        fprintf(stderr,"Cannot open input file!\n");
        show_usage(argv[0]);
    }
    output_file = fopen(argv[2],"w");
    if(!output_file) {
        fprintf(stderr,"Cannot open output file!\n");
        fclose(input_file);
        show_usage(argv[0]);
    }
    fprintf(output_file,"// Generated by ConvertBinaryFileToC.\n");
    fprintf(output_file,"// This converted file SHALL obey original licenses.\n");
    fprintf(output_file,"#include <Uefi.h>\n");
    fprintf(output_file,"GLOBAL_REMOVE_IF_UNREFERENCED const unsigned char %s[] = \"\\\n",argv[3]);
    size_t count = 0;
    int ch = fgetc(input_file);
    while(ch != EOF) {
        fprintf(output_file,"\\x%02x",ch);
        count++;
        if(count&&(!(count%16))) {
            fprintf(output_file,"\\\n");
        }
        ch = fgetc(input_file);
    }
    fprintf(output_file,"\";\n");
    fflush(output_file);
    fclose(output_file);
    fclose(input_file);
    printf("Convert done.%lld bytes written.\n",(long long)count);
}
